import Login from '@/components/Login'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Surendra Singh Kamboj | Portfoliio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-[100vh]'>
        <Login />
      </main>

    </>
  )
}
